### ISSUE TITLE
Q: how to achieve proper terminal settings to get CPM game "ladder" to display on Linux

### ISSUE THREAD

**Issue by godmar** [udo-munk/z80pack#174] opened 2022-10-15 13:54 UTC
First, I apologize for opening an issue here since this is certainly not a bug report but more of a user question.

I'm trying to play [ladder](https://en.wikipedia.org/wiki/Ladder_(video_game)), a 1982 CP/M game, on a Ubuntu 22.04 machine.

The ladder program outputs various terminal control escape sequences, such as `1b` `88`, `1b` `89`, etc., which I believe are [C1 8-bit control characters](https://www.xfree86.org/current/ctlseqs.html#C1%20(8-Bit)%20Control%20Characters).

My question, basically, is this: what combination of terminal emulator/terminal emulator settings/locale setting/font do people use to get a working CP/M terminal on a recent Linux distribution?

Here's what I tried:
```bash
LANG=C xterm -geometry 80x24 \
    -fn lucidasanstypewriter-bold-24 \
    -ti vt100 \
    +lc \
    -background black \
    -foreground green  &
```
This does not work.

Also, and again, this is more of a CP/M question, is there a difference between different versions of CP/M, like CPM2 vs CPM3 when it comes to the terminal?

I looked at the cpmsim source code and it appears that cpmsim simply outputs whatever the emulated machine outputs to its stdout (is that correct?), so presumably it relies on a faithful emulation in the environment.

**Comment by ratboy666** [comment] 2022-10-15 14:20
Godmar

The vt100 was released in 1978, so it is likely that ladder may not support it. You may try vt52, which xterm supports as well. CP/M itself really doesn’t care what sort of terminal you used — even 10cps teletypes worked

Note that vt100 (xterm) had an escape sequence to enter vt52 mode and reenter vt100 mode, works with xterm and not many others — xterm is generally the terminal emulator of choice for these applications. Consider vt340 Mode as that supports ReGIS (Gi Go ) graphics and sixel and tek 4014 as well
Sent from my iPhone

On Oct 15, 2022, at 9:55 AM, godmar ***@***.***> wrote:

﻿

First, I apologize for opening an issue here since this is certainly not a bug report but more of a user question.

I'm trying to play ladder<https://en.wikipedia.org/wiki/Ladder_(video_game)>, a 1982 CP/M game, on a Ubuntu 22.04 machine.

The ladder program outputs various terminal control escape sequences, such as 1b 88, 1b 89, etc., which I believe are C1 8-bit control characters<https://www.xfree86.org/current/ctlseqs.html#C1%20(8-Bit)%20Control%20Characters>.

My question, basically, is this: what combination of terminal emulator/terminal emulator settings/locale setting/font do people use to get a working CP/M terminal on a recent Linux distribution?

Here's what I tried:

LANG=C xterm -geometry 80x24 \
    -fn lucidasanstypewriter-bold-24 \
    -ti vt100 \
    +lc \
    -background black \
    -foreground green  &

This does not work.

Also, and again, this is more of a CP/M question, is there a difference between different versions of CP/M, like CPM2 vs CPM3 when it comes to the terminal?

I looked at the cpmsim source code and it appears that cpmsim simply outputs whatever the emulated machine outputs to its stdout (is that correct?), so presumably it relies on a faithful emulation in the environment.

**Comment by udo-munk** [comment] 2022-10-15 14:41
I have patched most CP/M games for VT-100 / ANSI terminals. A working ladder and the like is on the cpmsim hd-tools.dsk in user area 8.
For programs that cannot be patched for VT-100 (large escape sequences won't fit in patch area), I have patched them for VT-52, which xterm also can emaulate very well. For a VT-52 I use:

udos-mbp:cpmsim udo$ cat `which vt52`
#!/bin/sh

LC_ALL=C exec xterm -ti vt52 -tn vt52 -T "DEC VT-52" &

**Comment by udo-munk** [comment] 2022-10-15 14:48
CP/M 1 & 2 have no idea about the terminal connected to the machine. CP/M 3 at least has an idea about terminal width and high, which allows to ajust programs to a resized xterm <> 80x24.
That is what the vt100dyn RSX is about on the CP/M 3 disks, I prints some usage hints to the terminal console.

**Closed** 2022-10-16 10:27 UTC
